name: pixeldelta
channels:
  - conda-forge
  - defaults
dependencies:
  - python 3.8.12
  - gcc_linux-64 7.5.0
  - gxx_linux-64 7.5.0
  - boost
  - pocl
  - pyopencl
  - reikna
  - cmake
  - rust=1.56
  - cffi
  - pip
  - setuptools
